<div class="mdl-card__title"><strong>ddribin</strong> posted on 
		
			
				
				Oct 20, 2009 at 12:03:55 AM 
			
			
			
			
		
	</div><div class="mdl-card__supporting-text">
					Hi all,<div><br></div><div>I&apos;m interested in getting started on some NES programming just for kicks, and I&apos;ve been reading the Nerdy Nights series, along with some other docs. &#xA0;I&apos;m on a Mac, so I want to try translating these tutorials into ca65 and test on Nestopia, since that works better than NESASM3 +&#xA0;FCEUXD SP.</div><div><br></div><div>This first tutorial doesn&apos;t seem to work, however. &#xA0;The screen shows up as all black. &#xA0;I have to add in code like this to setup the palette before storing %10000000 into&#xA0;$2001:</div><div><br></div><div><br></div><div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>lda<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>#$3f<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>; Set PPU address to BG palette RAM ($3F00)</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>sta<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>$2006</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>lda<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>#$00</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>sta<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>$2006</div><div><br></div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>lda<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>#$00</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>sta<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>$2007</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>sta<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>$2007</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span></div><div>@vblankwait3:</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>bit<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>$2002</div><div><span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>bpl<span class="Apple-tab-span" style="white-space: pre; ">&#xA0;</span>@vblankwait3</div><div><br></div></div><div><br></div><div><div>Any help on why this is needed on Nestopia? &#xA0;Does it make sense that the palette needs to be setup like this? &#xA0;Is there a more proper way to initialize the PPU to get a light blue background by setting bit 7 of $2001? Is Nestopia just broken?</div><div><br></div><div>Thanks,</div><div><br></div><div>-Dave</div><div><br></div><div>P.S. Sorry for not formatting the code properly. I don&apos;t see how to choose a fixed width font.</div></div>
				</div><div class="mdl-card--border"></div>