
					<b><font size="5">The APU</font></b><br>
<br>
Music and sound effects on the NES are generated by the <b>APU</b> (Audio Processing Unit), the sound chip inside the CPU.&#xA0; The CPU &quot;talks&quot; to the APU through a series of I/O ports, much like it does with the PPU and joypads.<br>
<br>
PPU: $2000-$2007<br>
Joypads: $4016-$4017<br>
APU: $4000-$4015, $4017<br>
<br>
<b><font size="4">Channels</font></b><br>
<br>
The APU has 5 channels: Square 1, Square 2, Triangle, Noise and DMC.&#xA0; The first four play waves and are used in just about every game.&#xA0; The DMC channel plays samples (pre-recorded sounds) and is used less often.<br>
<br>
<b><font size="3"><font size="2">Square</font></font></b><br>
The square channels produce square waveforms.&#xA0; A square wave is named for its shape.&#xA0; It looks like this:<br>
&#xA0;
<div id="j.ge" style="text-align: left;"><img src="images/nerdy-nights-sound/square_wave.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/square_wave.jpg"></div>
<br>
As you can see the wave transitions instantaneously from its high point to its low point (where the lines are vertical).&#xA0; This gives it a hollow sound like a woodwind or an electric guitar.<br>
<br>
<b><font size="3"><font size="2">Triangle</font></font></b><br>
The triangle channel produces triangle waveforms.&#xA0; A triangle wave is also named for its shape.&#xA0; It looks like this:<br>
&#xA0;
<div id="rnep" style="text-align: left;"><img src="images/nerdy-nights-sound/triangle_wave.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/triangle_wave.jpg"></div>
<br>
The sound of a triangle wave is smoother and less harsh than a square wave. On the NES, the triangle channel is often used for bass lines (in low octaves) or a flute (in high octaves).&#xA0; It can also be used for drums.<br>
<br>
<font size="2"><b>Noise</b></font><br>
The noise channel has a random generator, which makes the waves it produces sound like.. noise.&#xA0; This channel is generally used for percussion and explosion sounds.<br>
<br>
<font size="2"><b>DMC</b></font><br>
The DMC channel plays samples, which are pre-recorded sounds.&#xA0; It is often used to play voice recordings (&quot;Blades of Steel&quot;) and percussion samples.&#xA0; Samples take up a lot of ROM space, so not many games make use of the DMC channel.<br>
<br>
<br>
<b><font size="4">Enabling Channels</font></b><br>
<br>
Before you can use the channels to produce sounds, you need to enable them.&#xA0; Channels are toggled on and off via port $4015:<br>
<br>
<span style="font-family: Courier New;">APUFLAGS ($4015)</span><br style="font-family: Courier New;">
<br style="font-family: Courier New;">
<span style="font-family: Courier New;">76543210</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; |||||</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; ||||+- Square 1 (0: disable; 1: enable)</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; |||+-- Square 2</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; ||+--- Triangle</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; |+---- Noise</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; +----- DMC</span><br>
<br>
Here are some code examples using $4015 to enable and disable channels:&#xA0; &#xA0;<br>
&#xA0; &#xA0;<br>
<span style="font-family: Courier New;">&#xA0;&#xA0; lda #%00000001</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; sta $4015 ;enable Square 1 channel, disable others</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; lda #%00010110</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; sta $4015 ;enable Square 2, Triangle and DMC channels.&#xA0; Disable Square 1 and Noise.</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; lda #$00</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; sta $4015 ;disable all channels</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; lda #$0F</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0; sta $4015 ;enable Square 1, Square 2, Triangle and Noise channels.&#xA0; Disable DMC.</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; ;this is the most common usage.</span><br>
&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; &#xA0;<br>
Try opening up some of your favorite games in FCEUXD SP and set a breakpoint on writes to $4015.&#xA0; Take a look at what values are getting written there.&#xA0; If you don&apos;t know how to do this, follow these steps:<br>
<br>
1. Open FCEUXD SP<br>
2. Load a ROM<br>
3. Open up the Debugger by pressing F1 or going to Tools-&gt;Debugger<br>
4. In the top right corner of the debugger, under &quot;BreakPoints&quot;, click the &quot;Add...&quot; button<br>
5. Type &quot;4015&quot; in the first box after &quot;Address:&quot;<br>
6. Check the checkbox next to &quot;Write&quot;<br>
7. Set &quot;Memory&quot; to &quot;CPU Mem&quot;<br>
8. Leave &quot;Condition&quot; and &quot;Name&quot; blank and click &quot;OK&quot;<br>
<br>
Now FCEUX will pause emulation and snap the debugger anytime your game makes a write (usually via STA) to $4015.&#xA0; The debugger will tell you the contents of the registers at that moment, so you can check what value will be written to $4015.&#xA0; Some games will write to $4015 every frame, and some only do so once at startup.&#xA0; Try resetting the game if your debugger isn&apos;t snapping.<br>
<br>
What values are being written to $4015?&#xA0; Can you tell what channels your game is using?<br>
<br>
<br>
<b><font size="4">Square 1 Channel</font></b><br>
<br>
Let&apos;s make a beep.&#xA0; This week we&apos;ll learn how to produce a sound on the Square 1 channel.&#xA0; The Square channels are everybody&apos;s favorites because you can control the volume and tone and perform sweeps on them.&#xA0; You can produce a lot of interesting effects using the Squares.<br>
<br>
Square 1 is controlled via ports $4000-$4003.&#xA0; The first port, $4000, controls the duty cycle (ie, tone) and volume for the channel.&#xA0; It looks like this:<br>
<br>
<span style="font-family: Courier New;">SQ1_ENV ($4000)</span><br style="font-family: Courier New;">
<br style="font-family: Courier New;">
<span style="font-family: Courier New;">76543210</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">||||||||</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">||||++++- Volume</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">|||+----- Saw Envelope Disable (0: use internal counter for volume; 1: use Volume for volume)</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">||+------ Length Counter Disable (0: use Length Counter; 1: disable Length Counter)</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">++------- Duty Cycle</span><br>
<br>
For our purposes, we will focus on Volume and Duty Cycle.&#xA0; We will set Saw Envelope Disable and Length Counter Disable to 1 and then forget about them.&#xA0; If we leave Saw Envelopes on, the volume of the channel will be controlled by an internal counter.&#xA0; If we turn them off, WE have control of the volume.&#xA0; If WE have control, we can code our own envelopes (much more versatile).&#xA0; Same thing with the Length Counter.&#xA0; If we disable it, we have more control over note lengths.&#xA0; If that didn&apos;t make sense, don&apos;t worry.&#xA0; It will become clearer later.&#xA0; For now we&apos;re just going to disable and forget about them.<br>
<br>
<i>Volume</i> controls the channel&apos;s volume.&#xA0; It&apos;s 4 bits long so it can have a value from 0-F.&#xA0; A volume of 0 silences the channel.&#xA0; 1 is very quiet and F is loud.<br>
<br>
<i>Duty Cycle</i> controls the tone of the Square channel.&#xA0; It&apos;s 2 bits long, so there are four possible values:<br>
<br>
00 = a weak, grainy tone.&#xA0; Think of the engine sounds in RC Pro-Am. (12.5% Duty)<br>
01 = a solid mid-strength tone. (25% Duty)<br>
10 = a strong, full tone, like a clarinet or a lead guitar (50% Duty)<br>
11 = sounds a lot like 01 (25% Duty negated)<br>
<br>
The best way to know the difference in sound is to listen yourself.&#xA0; I recommend downloading <a href="http://famitracker.shoodot.net/" target="_blank" original-href="http://famitracker.shoodot.net/">FamiTracker</a> and playing with the different Duty settings in the Instrument Editor.<br>
<br>
For those interested, Duty Cycle actually refers to the percentage of time that the wave is in &quot;up&quot; position vs. &quot;down&quot; position.&#xA0; Here are some pictures:<br>
<br>
12.5%
<div id="f0:l" style="text-align: left;"><img src="images/nerdy-nights-sound/square_wave_125_duty.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/square_wave_125_duty.jpg"></div>
25%<br><br><div id="ilti" style="text-align: left;"><img src="images/nerdy-nights-sound/square_wave_25_duty.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/square_wave_25_duty.jpg"></div>
50%<br><br><div id="bjx0" style="text-align: left;"><img src="images/nerdy-nights-sound/square_wave_50_duty.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/square_wave_50_duty.jpg"></div>
25% negated<br><br><div id="qi76" style="text-align: left;"><img src="images/nerdy-nights-sound/square_wave_25neg_duty.jpg" style="width: 240px; height: 50px;" original-src="http://tummaigames.com/square_wave_25neg_duty.jpg"></div>
<br>
Don&apos;t sweat it if graphs and waves aren&apos;t your thing.&#xA0; Use your ears instead.<br>
<br>
Here&apos;s a code snippet that sets the Duty and Volume for the Square 1 channel:<br>
<br>
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; lda #%10111111; Duty 10 (50%), volume F (max!)</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; sta $4000</span><br>
<br>
$4001 controls sweeps for Square 1.&#xA0; We&apos;ll skip them for now.<br>
<br>
<font size="2"><b>Setting the Note</b></font><br>
$4002 and $4003 control the period of the wave, or in other words what note you hear (A, C#, G, etc).&#xA0; Periods are 11-bits long.&#xA0; $4002 holds the low 8-bits and $4003 holds the high 3-bits of the period.&#xA0; We&apos;ll get into more detail in a future tutorial, but for now just know that changing the values written to these ports will change the note that is played.<br>
<br>
<span style="font-family: Courier New;">SQ1_LO ($4002)</span><br style="font-family: Courier New;">
<br style="font-family: Courier New;">
<span style="font-family: Courier New;">76543210</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">||||||||</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">++++++++- Low 8-bits of period</span><br style="font-family: Courier New;">
<br style="font-family: Courier New;">
<span style="font-family: Courier New;">SQ1_HI ($4003)</span><br style="font-family: Courier New;">
<br style="font-family: Courier New;">
<span style="font-family: Courier New;">76543210</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">||||||||</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">|||||+++- High 3-bits of period</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">+++++---- Length Counter</span><br>
<br>
The Length Counter, if enabled, controls how long the note is played.&#xA0; We disabled it up in the $4000 section, so we can forget about it for now.<br>
<br>
Here is some code that will produce an eternal beep on the Square 1 channel:<br>
<br>
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; lda #%00000001</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; sta $4015 ;enable square 1</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; lda #%10111111 ;Duty 10, Volume F</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; sta $4000</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; lda #$C9&#xA0;&#xA0;&#xA0; ;0C9 is a C# in NTSC mode</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; sta $4002</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; lda #$00</span><br style="font-family: Courier New;">
<span style="font-family: Courier New;">&#xA0;&#xA0;&#xA0; sta $4003</span><br>
&#xA0;&#xA0; &#xA0;<br>
<b>Putting It All Together</b><br>
Download and unzip the <a href="downloads/NerdyNightsSoundSourceCollection/square1.zip" target="_blank" original-href="http://tummaigames.com/square1.zip">square1.zip</a> sample files. All the code above is in the square1.asm file. Make sure square1.asm and square1.bat are all in the same folder as NESASM3, then double click square1.bat. That will run NESASM3 and should produce the square1.nes file. Run that NES file in FCEUXD SP to listen to your beep!&#xA0; Edit square1.asm to change the Volume (0 to F), or to change the Duty Cycle for the square wave.&#xA0; Try changing the period to produce different notes.<br>
<br>
<b>Next Week</b>: <a href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=22610" target="_blank" original-href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=22610">Square 2 and Triangle.&#xA0; Multiple beeps!</a>
				