
					<u>Introduction to the Series</u><br>
&#xA0;<br>
Welcome to World Building with SGP! What follows is a series of reflections that have spawned from my own experiences attempting to learn NES programming. I am not an expert when it comes to writing code, drawing graphics, composing sound, or designing levels, but hopefully these thoughts will be of use to someone. I plan to add to these reflections as I attempt new aspects of game development, and earlier lessons will be refined as my knowledge and experience grow. These are very much an extension of what I have learned here on NA and through reading various articles on NESDEV and elsewhere, and a cumulative bibliography will be added at some point. Please comment, critique (constructively one hopes), and discuss things as you see fit. This initial post will serve as a table of contents of sorts, and each chapter will have its own thread. Keep a lookout for an alternative form of presentation in the future too. Also, please note that they are written mainly with an eye toward creating overhead adventure games. As I attempt other game play perspectives, thoughts on these will be incorporated.<br>
&#xA0;<br>
These lessons, articles, what have you are intended for different types of people. On the one hand, they are for programmers setting out on the long journey that is NES development. Perhaps more importantly, though, my hope is that they reach people within our community who do not really have an interest in programming, but who would like to be involved with game development at one&#xA0;level or another. We have already witnessed what can happen when highly talented people collaborate (several <em>8-Bit Christmas</em> games, the <em>Battle Kids</em>, MRN&#x2019;s various games, <em>T-Gun</em>, <em>Nomolos </em>and<em> Owlia</em>, and many others), though most contributions have been more musically inclined. Eventually, I hope to discuss music, but the first set of lessons will primarily&#xA0;deal with art.&#xA0;For most programmers, well, many at least, graphics are a huge time sink. We can usually get decent results with enough patience, but that is valuable time lost that could be spent actually completing games. My current main character, for example, has already taken somewhere between twenty and thirty hours to draw, and there are still several poses to go. Hopefully these initial&#xA0;discussions will help a few to take up the challenge of learning how to draw within the structures of the NES.<br>
&#xA0;<br>
One last thing. About every month or so, we see someone pop into the Brewery with a suggestion for a game, or asking how to convert &#x201C;X&#x201D; game to the NES. We are familiar with the results of these, and the various arguments that are exchanged on either side. One of the most important points that is brought up, in my own opinion anyways, is that those taking the time to learn how to actually program already have plenty of ideas, and are not likely to take up someone else&#x2019;s project. There is certainly truth in it, and even with detailed write ups at the design level, few are going to actually do someone else&#x2019;s work for them. I would think, however, that if someone really took the time to create a world at the artistic level, the response would be much warmer. Mind you, it would take hundreds of hours to do so, which would also help to prove&#xA0;one&apos;s seriousness and commitment. Still, if seeking collaboration, this might be a way to go. Draw some things, show us what you can do, and then hopefully mutual collaboration can ensue. Just a thought though, and I can only speak for myself in this regard.<br>
&#xA0;<br>
&#xA0;<br>
&#xA0;
<div>
	<u>Table of Contents</u>:</div>
&#xA0;<br>
Chapter 1: Foundations <a href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=137055" target="_blank" original-href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=137055">http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;am...</a> <br>
Chapter 2: Introduction to NES Graphics Editors <a href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=137056" target="_blank" original-href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=137056">http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;am...</a> <br>
&#xA0;<br>
&#xA0;<br>
				