
					<a href="http://www.nintendoage.com/forum/messageview.cfm?catid=22&amp;threadid=8172" target="_blank">Previous Week</a> - Backgrounds<div><br></div><div><span class="Apple-style-span" style="font-weight: bold; ">This Week:</span> &#xA0;Most of this lesson is about how to organize and structure your game. &#xA0;Subroutines and game states help arrange the code for easier reading and reuse of code. &#xA0;</div><div><br></div><div><br></div><div><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; "><b><span class="Apple-style-span" style="font-size: medium; ">Variables</span></b></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">As covered in week 1, variables are data stored in RAM that you can change any time.&#xA0; The sprite data in RAM is all variables.&#xA0; You will need more variables for keeping track of things like the score in the game.&#xA0; To do that you first need to tell NESASM where in RAM to put the variable.&#xA0; This is done using the .rsset and .rs directives.&#xA0; First .rsset is used to set the starting address of the variable.&#xA0; Then .rs is used to reserve space.&#xA0; Usually just 1 byte is reserved, but you can have as much as you want.&#xA0; Each time you do a .rs the address gets incremented so you don&apos;t need to do .rsset again.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; .rsset $0000&#xA0; &#xA0; ;put variables starting at 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; score1 &#xA0; .rs 1&#xA0; ;put score for player 1 at $0000</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; score2 &#xA0; .rs 1&#xA0; ;put score for player 2 at $0001</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; buttons1 .rs 1&#xA0; ;put controller data for player 1 at $0002</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; buttons2 .rs 1&#xA0; ;put controller data for player 2 at $0003</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Once you set the address for the variable, you do not need to know the address anymore.&#xA0; You can just reference it using the variable name you created.&#xA0; You can insert more variables above the current ones and the assembler will automatically recalculate the addresses.</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><br></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><span class="Apple-style-span" style="font-size: 16px; font-weight: bold; ">Constants</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><span class="Apple-style-span" style="font-size: 16px; font-weight: bold; "><span class="Apple-style-span" style="font-size: 12px; font-weight: normal; ">Constants are numbers that you do not change.&#xA0; They are just used to make your code easier to read.&#xA0; In Pong an example of a constant would be the position of the outer walls.&#xA0; You will need to compare the ball position to the walls to make the ball bounce, but the walls do not change so they are good constants.&#xA0; Doing a compare to LEFTWALL is easier to read and understand than a comparison to $F6.</span></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">To declare constants you use the = sign:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; color: rgb(0, 116, 0); "><span>&#xA0; RIGHTWALL&#xA0; &#xA0; &#xA0; = $</span><span>02</span><span>&#xA0;</span><span style="letter-spacing: 0px; ">; when ball reaches one of these, do something</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; TOPWALL&#xA0; &#xA0; &#xA0; &#xA0; = $</span><span>20</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BOTTOMWALL &#xA0; &#xA0; = $D8</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LEFTWALL &#xA0; &#xA0; &#xA0; = $F6</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">The assembler will then do a find/replace when building your code.</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><br><span style="letter-spacing: 0px; "></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; "><b><span class="Apple-style-span" style="font-size: medium; ">Subroutines</span></b></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">As your program gets larger, you will want subroutines for organization and to reuse code.&#xA0; Instead of progressing linearly down your code, a subroutine is a block of code located somewhere else that you jump to, then return from.&#xA0; The subroutine can be called at any time, and used as many times as you want.&#xA0; Here is what some code looks like without subroutines:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">RESET:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; SEI&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable IRQs</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; CLD&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable decimal mode</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">vblankwait1: &#xA0; &#xA0; &#xA0; ; First wait for vblank to make sure PPU is ready</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BIT $2002</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BPL vblankwait1</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">clrmem:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA #$FE</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; STA $0200, x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; INX</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BNE clrmem</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; ">&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">vblankwait2:&#xA0; &#xA0; &#xA0; ; Second wait for vblank, PPU is ready after this</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BIT $2002</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BPL vblankwait2</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Notice that the vblankwait is done twice, so it is a good choice to turn into a subroutine.&#xA0; First the vblankwait code is moved outside the normal linear flow:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">vblankwait:&#xA0; &#xA0; &#xA0; ; wait for vblank</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BIT $2002</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BPL vblankwait</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">RESET:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; SEI&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable IRQs</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; CLD&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable decimal mode</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">clrmem:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA #$FE</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; STA $0200, x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; INX</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BNE clrmem</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Then that code needs to be called, so the JSR (Jump to SubRoutine) instruction is where the vblankwait code used to be:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">RESET:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; SEI&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable IRQs</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; CLD&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable decimal mode</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; JSR vblankwait&#xA0; ;;jump to vblank wait #1</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">clrmem:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA #$FE</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; STA $0200, x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; INX</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BNE clrmem</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; JSR vblankwait&#xA0; ;; jump to vblank wait again</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">And then when the subroutine has finished, it needs to return back to the spot it was called from.&#xA0; This is done with the RTS (ReTurn from Subroutine) instruction.&#xA0; The RTS will jump back to the next instruction after the JSR:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; vblankwait:&#xA0; &#xA0; &#xA0; ; wait for vblank&#xA0; &lt;--------</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; BIT $2002&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; \</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; BPL vblankwait&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;----- RTS &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">/&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; RESET:&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; SEI&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable IRQs &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; CLD&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; disable decimal mode &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; JSR vblankwait&#xA0; ;;jump to vblank wait #1 --/</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">\--&gt; clrmem:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; LDA #$FE</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; STA $0200, x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; INX</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; BNE clrmem</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; JSR vblankwait&#xA0; ;; jump to vblank wait again, returns here</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; "><b><span class="Apple-style-span" style="font-size: medium; ">Better Controller Reading</span></b></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Now that you can set up subroutines, you can do much better controller reading.&#xA0; Previously the controller was read as it was processed.&#xA0; With multiple game states, that would mean many copies of the same controller reading code.&#xA0; This is replaced with one controller reading subroutine that saves the button data into a variable.&#xA0; That variable can then be checked in many places without having to read the whole controller again.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ReadController:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA #$01</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; STA $4016</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA #$00</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; STA $4016</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDX #$08</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ReadControllerLoop:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LDA $4016</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; LSR A &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ; bit0 -&gt; Carry</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; ROL buttons &#xA0; &#xA0; ; bit0 &lt;- Carry</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; DEX</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; BNE ReadControllerLoop</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; RTS</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 11px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">This code uses two new instructions.&#xA0; The first is LSR (Logical Shift Right).&#xA0; This takes each bit in A and shifts them over 1 position to the right.&#xA0; Bit 7 is filled with a 0, and bit 0 is shifted into the Carry flag.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">bit number&#xA0; &#xA0; &#xA0; 7 6 5 4 3 2 1 0&#xA0; carry</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">original data &#xA0; 1 0 0 1 1 0 1 1&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; \ \ \ \ \ \ \&#xA0; \</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; \ \ \ \ \ \ \&#xA0; \&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">shifted data&#xA0; &#xA0; 0 1 0 0 1 1 0 1&#xA0; 1</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Each bit position is a power of 2, so LSR is the same thing as divide by 2.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">The next new instruction is ROL (ROtate Left) which is the opposite of LSR.&#xA0; Each bit is shifted to the left by one position.&#xA0; The Carry flag is put into bit 0.&#xA0; This is the same as a multiply by 2.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">These instructions are used together in a clever way for controller reading.&#xA0; When each button is read, the button data is in bit 0.&#xA0; Doing the LSR puts the button data into Carry.&#xA0; Then the ROL shifts the previous button data over and puts Carry back to bit 0.&#xA0; The following diagram shows the values of Accumulator and buttons data at each step of reading the controller:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; Accumulator &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; buttons data</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">bit: &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 7&#xA0; 6&#xA0; 5&#xA0; 4&#xA0; 3&#xA0; 2&#xA0; 1&#xA0; 0&#xA0; Carry &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 7&#xA0; 6&#xA0; 5&#xA0; 4&#xA0; 3&#xA0; 2&#xA0; 1&#xA0; 0&#xA0; Carry&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">read button A&#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">LSR A&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ROL buttons&#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; ">&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">read button B&#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; B&#xA0; 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">LSR A&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; B &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; B</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ROL buttons&#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; B&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; ">&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">read button SEL&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 SEL 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">LSR A&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 SEL&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A SEL</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ROL buttons&#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; B SEL 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">read button STA&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 STA 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">LSR A&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 STA&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A STA</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">ROL buttons&#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0 &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; 0&#xA0; 0&#xA0; 0&#xA0; 0&#xA0; A&#xA0; B SEL STA 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 11px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 11px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">The loop continues for a total of 8 times to read all buttons.&#xA0; When it is done there is one button in each bit:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">bit: &#xA0; &#xA0; &#xA0; 7 &#xA0; &#xA0; 6 &#xA0; &#xA0; 5 &#xA0; &#xA0; 4 &#xA0; &#xA0; 3 &#xA0; &#xA0; 2 &#xA0; &#xA0; 1 &#xA0; &#xA0; 0</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">button:&#xA0; &#xA0; A &#xA0; &#xA0; B &#xA0; select start&#xA0; up &#xA0; down&#xA0; left right</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">If the bit is 1, that button is pressed.</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><br><span style="letter-spacing: 0px; "></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; "><b><span class="Apple-style-span" style="font-size: medium; ">Game Layout<span class="Apple-style-span" style="font-size: 12px; font-weight: normal; "></span></span></b></span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; "><b><span class="Apple-style-span" style="font-size: medium; "><span class="Apple-style-span" style="font-size: 12px; font-weight: normal; ">The Pong game engine will use the typical simple NES game layout.&#xA0; First all the initialization is done.&#xA0; This includes clearing out RAM, setting up the PPU, and loading in the title screen graphics.&#xA0; Then it enters an infinite loop, waiting for the NMI to happen.&#xA0; When the NMI hits the PPU is ready to accept all graphics updates.&#xA0; There is a short time to do these so code like sprite DMA is done first.&#xA0; When all graphics are done the actual game engine starts.&#xA0; The controllers are read, then game processing is done.&#xA0; The sprite position is updated in RAM, but does not get updated until the next NMI.&#xA0; Once the game engine has finished it goes back to the infinite loop.</span></span></b></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">Init Code -&gt; Infinite Loop -&gt; NMI -&gt; Graphics Updates -&gt; Read Buttons -&gt; Game Engine --\</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; ^&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; \------------------------------------------------------------------/</span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><br><span style="letter-spacing: 0px; "></span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><span style="letter-spacing: 0px; "></span></p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; min-height: 14px; "><span class="Apple-style-span" style="font-size: 16px; font-weight: bold; ">Game State</span><span style="letter-spacing: 0px; "></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">The use of a &quot;game state&quot; variable is a common way to arrange code.&#xA0; The game state just specifies what code should be run in the game engine each frame.&#xA0; If the game is in the title screen state, then none of the ball movement code needs to be run.&#xA0; A flow chart can be created that includes what each state should do, and the next state that should be set when it is done.&#xA0; For Pong there are just 3 basic states.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;-&gt;Title State&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; /--&gt; Playing State&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; /--&gt;&#xA0; Game Over State</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">/ &#xA0;wait for start button --/ &#xA0; &#xA0; move ball &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; /&#xA0; &#xA0; &#xA0; wait for start button -\</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; move paddles &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; | &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; \</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; check for collisions &#xA0; / &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">|&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; check for score = 15 -/&#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; |</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;\ &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; &#xA0; /</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; \-----------------------------------------------------------------------------------/&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><br><span style="letter-spacing: 0px; "></span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">The next step is to add much more detail to each state to figure out exactly what is needed.&#xA0; These layouts are done before any significant coding starts.&#xA0; Some of the game engine like the second player and the score will be added later.&#xA0; Without the score there is no way to get to the Game Over State yet.</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">Title State:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; if start button pressed</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; turn screen off</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; load game screen</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; set paddle/ball position</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; go to Playing State</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; turn screen on</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">Playing State:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; move ball</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if ball moving right</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; add ball speed x to ball position x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; if ball x &gt; right wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; bounce, ball now moving left</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if ball moving left</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; subtract ball speed x from ball position x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; if ball x &lt; left wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; bounce, ball now moving right</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if ball moving up</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; subtract ball speed y from ball position y</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; if ball y &lt; top wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; bounce, ball now moving down</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if ball moving down</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; add ball speed y to ball position y</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; if ball y &gt; bottom wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0;&#xA0; &#xA0; &#xA0; &#xA0; bounce, ball now moving up</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; if up button pressed</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if paddle top &gt; top wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; move paddle top and bottom up</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; if down button pressed</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if paddle bottom &lt; bottom wall</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; move paddle top and bottom down</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; ">&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; if ball x &lt; paddle1x</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; if ball y &gt; paddle y top</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; if ball y &lt; paddle y bottom</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; &#xA0; &#xA0; bounce, ball now moving left</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">Game Over State:</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; if start button pressed</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; turn screen off</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; load title screen</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; go to Title State</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; "><span style="letter-spacing: 0px; ">&#xA0; &#xA0; turn screen on</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; ">&#xA0;</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span style="letter-spacing: 0px; "></span><br></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 11px; font: normal normal normal 10px/normal Monaco; min-height: 14px; "><span class="Apple-style-span" style="font-family: Helvetica; font-size: 16px; font-weight: bold; ">Putting It All Together</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Download and unzip the <a href="scraper/files/pong1.zip" target="_blank">pong1.zip</a> sample files.&#xA0; The playing game state and ball movement code is in the pong1.asm file. Make sure that file, mario.chr, and pong1.bat is in the same folder as NESASM3, then double click on pong1.bat. That will run NESASM3 and should produce pong1.nes. Run that NES file in FCEUXD SP to see the ball moving!</span></p>
<p style="margin-top: 0px; margin-right: 0px; margin-bottom: 12px; margin-left: 0px; font: normal normal normal 12px/normal Helvetica; "><span style="letter-spacing: 0px; ">Other code segments have been set up but not yet completed.&#xA0; See how many of those you can program yourself.&#xA0; The main parts missing are the paddle movements and paddle/ball collisions.&#xA0;&#xA0;You can also add the intro state and the intro screen, and the playing screen using the background information from the previous week.</span></p></div><div><br></div>
				