<div class="mdl-card__title"><strong>albailey</strong> posted on 
		
			
				
				May 15, 2010 at 8:36:36 PM 
			
			
			
			
		
	</div><div class="mdl-card__supporting-text">
					<div class="FTQUOTE"><i>Originally posted by: <b>Mario&apos;s Right Nut</b></i><br><br><div class="FTQUOTE"><p><i>Originally posted by: <b>deleteme</b></i><br><br>Wow all that to avoid an simple apology, and yet still the tutorial has problems! </p><p>-Sorry to bunnyboy for using &quot;his&quot; name.&#xA0; I assumed it was an NA name.&#xA0; he should have said something.<br>A: INES header mirror info is wrong </p><p>-&#xA0;Not wrong.&#xA0; Using 4 screen mirroring.&#xA0; Besides, the mapper controls it anyway.<br>B: nothing about batt ram </p><p>-Not using it, so ignored it.<br>C: still doesnt explain about the reset </p><p>-This is explained enough to make it work just fine.<br>D: wrong caps on kb </p><p>-So what?<br>e: misspelled words </p><p>-So what?<br>F: doesnt explain bits7,6,5 </p><p>-tell me what they do and I&apos;ll add them.<br>G: etc etc etc </p><p>-<img src="images/blank.gif" border="0" style="display: none;" original-src="/media/_images/expressions/teabag.gif"> <img src="images/blank.gif" border="0" style="display: none;" original-src="/media/_images/expressions/teabag.gif"> <img src="images/blank.gif" border="0" style="display: none;" original-src="/media/_images/expressions/teabag.gif"><br>why miss the chance to make it better? At least BunnyBoy fixes his shit when an error is found... <br><br>&quot;Someone will help me out if there are any mistakes.&quot; and when help came it was deleted. Will you take the help now?</p></div><br><br>My point was to give someone the code to make a working program with a working understanding.&#xA0; Not to explain exactly what everything did and why.&#xA0; That&apos;s why I referenced NesDev wiki.&#xA0; <img src="images/blank.gif" border="0" style="display: none;" original-src="/media/_images/expressions/face-icon-small-smile.gif"><br></div><div><br></div>I like helping people too. &#xA0; &#xA0;I think the person may have just been in a bad mood.<br><br>You should change the caps on kb. &#xA0; It actually <u>is</u> important. &#xA0; The k doesn&apos;t matter. &#xA0;The b does.
<div>256 kb = 32 kB</div><div>b = bit</div><div>B = byte</div><div><br></div><div>Bit 7 is important. &#xA0;&#xA0;<a href="http://wiki.nesdev.com/w/index.php/MMC1" target="_blank" original-href="http://wiki.nesdev.com/w/index.php/MMC1">http://wiki.nesdev.com/w/index.php/MMC1</a></div><div>From that page, a value of 1 =&#xA0;<span class="Apple-style-span" style="font-family: monospace; font-size: 13px; line-height: 14px; white-space: pre; ">locking PRG ROM at $C000-$FFFF to the last bank.</span></div><div><span class="Apple-style-span" style="font-family: monospace; font-size: 13px; line-height: 14px; white-space: pre; "><br></span></div><div>The nesdevwiki doesnt have any info about bits 6 and 5 either, so I would assume they are unimportant.</div><div><br></div><div>I also assume that battery backed ram requires no additional coding. &#xA0; I always thought the battery keeps the data from going away, the same as a battery on a motherboard keeps the BIOS settings from being wiped on a power down. &#xA0;</div><div><br></div><div>- Edited to fix a bug in my response.</div><div><br></div><div>Al</div>
				</div><div class="mdl-card--border"></div>